image: docker:git
services:
- docker:dind


stages:
- build
- package
- clean


build:

  image: maven:3.5.4-jdk-8-alpine

  stage: build
  script:
    -  curl -fL https://getcli.jfrog.io | sh
    # Configure Artifactory instance with JFrog CLI
    - ./jfrog rt config --url=$ARTIFACTORY_URL --user=$ARTIFACTORY_USER --password=$ARTIFACTORY_PASS
    - ./jfrog rt c show
    # Set the M2_HOME environment variable
    - export M2_HOME=/usr/share/maven
    # Replace the repository name in the configuration.yml to the correct one.
    # - sed -i 's,MAVEN_REPO_KEY,'"$MAVEN_REPO_KEY"',g' configuration.yml
    # - mvn clean install
    - ./jfrog rt mvn "clean install" maven.conf --build-name=gitlabci-maven-artifactory --build-number=$CI_JOB_ID
  
  when: manual