image: docker:git
services:
- docker:dind


stages:
- build
- package
- clean


build:

  image: maven:3.5.4-jdk-8-alpine

  stage: build
  script:
    # - apk update && apk upgrade && apk add git 
    - apk add git 
    # Set the M2_HOME environment variable
    - export M2_HOME=/usr/share/maven
    
    - curl -fL https://getcli.jfrog.io | sh
    # Configure Artifactory instance with JFrog CLI
    - ./jfrog rt config --url=$ARTIFACTORY_URL --user=$ARTIFACTORY_USER --password=$ARTIFACTORY_PASS
    - ./jfrog rt c show
 
    - ./jfrog rt bce gitlabci-maven-artifactory $CI_JOB_ID

    - ./jfrog rt bag gitlabci-maven-artifactory $CI_JOB_ID --config jira-cli.conf

    - ls -la
    - ./jfrog rt sp "maven-test/JetbrainsCrack/JetbrainsCrack/3.1-release/JetbrainsCrack-3.1-release.jar" "Jira_issue=http://test.jira.com/"
    
    - ./jfrog rt sp "maven-test/JetbrainsCrack/JetbrainsCrack/3.1-release/JetbrainsCrack-3.1-release.jar" "qulity.gate.sonarUrl=http://192.168.230.158:9000/dashboard/index/gitlabci-maven-artifactory"
    
    - issue_id=buildInfo.env.CI_COMMIT_MESSAGE
    - echo $issue_id
    # Pass the build information to Artifactory  
    - ./jfrog rt bp gitlabci-maven-artifactory $CI_JOB_ID

    
  when: manual
