name: Fetch OIDC Token

on: [push]

jobs:
  fetch-token:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Request OIDC Token
        id: request_token
        run: |
          echo "Requesting OIDC Token"
          response=$(curl -H "User-Agent: actions/oidc-client" -H "Authorization: Bearer $ACTIONS_ID_TOKEN_REQUEST_TOKEN" \
          "${ACTIONS_ID_TOKEN_REQUEST_URL}")
          echo "::add-mask::$response"
          echo "OIDC Response: $response"

      - name: Print OIDC Token
        run: |
          echo "OIDC Token Response: ${{ steps.request_token.outputs.response }}"
